---
version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres_hoi-philoi
    ports: 
      - 5432:5432
    volumes:
      - ~/databases/postgres:/var/lib/postgresql/data
    env_file:
      - ./.db.env
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    container_name: minio_hoi-philoi
    command: server /data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090
    volumes: 
      - ~/databases/minio/data:/data
    env_file:
      - ./.db.env
    restart: unless-stopped
  
  hoi-philoi:
    image: hoi-philoi
    container_name: hoi-philoi
    ports:
      - 4000:4000
    depends_on:
      - minio
      - postgres
    restart: unless-stopped

